# -*- coding: utf-8 -*-
"""CRISP-DM analysis Premier League.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TuxjKteM8wpHOb8NsdnO68Zs0bacfcWd
"""

import pandas as pd

data = pd.read_csv('eplmatches.csv')

data.head()

data.describe()

data.tail()

